version: "3.4"
networks:
  dockerapi-dev:
    driver: bridge
services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=User ID=mysqluser;Password=mysqlpassword;Host=selah-db;Database=selah_db
      - INTEGRATION_TEST_DB=User ID=mysqluser;Password=mysqlpassword;Host=selah-db-test;Database=selah_db_test
    ports:
      - 8080:80
    env_file: secrets.env
    depends_on:
      - "selah-db"
    volumes:
      - ~/.aspnet/https:/ASP.NET/Https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

    networks:
      - dockerapi-dev
  selah-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=selah_db
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - dockerapi-dev

  selah-db-test:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=selah_db_test
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
    ports:
      - "3307:3306"
    volumes:
      - db-test:/var/lib/mysql
    networks:
      - dockerapi-dev
volumes:
  db:
    driver: local
  db-test:
    driver: local
