apiVersion: v1
kind: Service
metadata:
  name: selah-api-production
  labels:
    app: selah-api-production
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: selah-api-production
  type: LoadBalancer