name: Build Postgres Test Container and Run Migrations

jobs:
  build postgres:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
  
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./utilities/DbMigrationRunner.sln
      - name: Build Migration Project
        run: dotnet build ./utilities/DbMigrationRunner.sln --no-restore
      - name: Run Migrations
        run: dotnet run --project ./utilities/DbMigrationRunner